### ISSUE TITLE
Missing line breaks

### ISSUE THREAD

**Issue by mbrowne** [rainforestapp/rainforest-cli#369]
If the test steps contain line breaks, it seems that line breaks are not included in the downloaded files after running `rainforest download`.

Here is the output of the rainforest version command on my machine:

```
$ rainforest -v
Rainforest CLI version 2.15.1 - stable channel - build: 0f08e76f
```

**Comment by mbrowne** [comment]
Related question: How can I add line breaks to tests when uploading them? I tried adding `\n` but it just interpreted it literally.

**Comment by roman-dowakin** [comment]
Hi, Matt!

Thank you for reporting this. Currently it's not supported in rainforest-cli, because RFML format does not support escaping.

I've added this problem to internal Jira board. I will post future updates here.
I can propose workaround, but it's pretty hacky. You can create custom variable equal to new line, and after use custom variable in RFML.

**Comment by ukd1** [comment]
@mbrowne, I'm going to close this issue as it's not supported in RFML on purpose. To fix would likely mean a large, breaking change to the format. 

If you'd like to tell us the use case, we can help you with a work-around, or rethink our position.
